### ISSUE TITLE
Configurable release tarball name?

### ISSUE THREAD

**Issue by deniseyu** [concourse/bosh-io-release-resource#10]
Hi folks,

I was wondering if you have any bandwidth to make it possible to configure the name of the release tarball to something other than `release.tgz`.

The use case is that, as our pipeline is currently configured, having multiple bosh.io resources will cause the first tarball file to be overwritten by the second, as they all end up living in the same directory within task container. If you'd like more context please let me know, I'd be happy to chat over Slack or email.

We have some potential workarounds from the consumer side but they're not pretty :(

Thanks.

**Comment by chendrix** [comment]
@deniseyu I'm confused. Every individual resource `get` should fetch a `release.tgz` into its relevant input folder.

So for instance if your task has `garden-runc-release` and `concourse-release` it would fetch `garden-runc-release/release.tgz` and `concourse-release/release.tgz`

How exactly are your tarballs "overwriting" each other?

**Comment by deniseyu** [comment]
Hey @chendrix thanks for the quick reply.

We currently use a medley of S3 and Github resources, which both use whatever the name of the tarball is. Under present convention, they follow the format `{release}-{version}.tgz`. 

We have some code that moves all of these tarballs to the same directory, and essentially we'd like to avoid doing an if/then check on the tarball's name, then renaming it just before the move takes place. This is admittedly a bit of legacy implementation from our end, but given that S3 resource output paths can be configured using a regex, we figured we'd ask.

Another possible way to guarantee unique filenames might be to use the name of the release, ie. `loggregator/loggregator.tgz`.

This isn't blocking us, it'd just be something that would be nice to have in a future release. We'd be happy to implement either option and send a PR if you're open to that.

**Comment by deniseyu** [comment]
@henderjm @cghsystems

**Comment by vito** [comment]
I've been wanting to do this; had a story for it a while ago: https://www.pivotaltracker.com/story/show/91865930

Our use case is a bit simpler; it'd be nice to just be able to upload the file as-is to our GitHub releases without having to rename it (since we upload `garden-runc` to our own releases).

I wouldn't make it configurable; we can probably just rename it. A common pattern at the moment is to just say `<name>/*.tgz`, which will still work once it's renamed. If we try to be backwards-compatible and have `release.tgz` as a symlink that glob would then match *two* files, which would be bad.

The story is marked `blocked` because the information isn't available from the `bosh.io` API. We could extract the metadata from the `.tgz` to discover the name I guess.

In any case we probably won't get to this ourselves. Resources are pretty easy to contribute to, so we tend to focus our small team's efforts on core Concourse functionality. I'd be happy to review a PR for this.

**Comment by jtarchie** [comment]
We are considering this issue dead due to inactivity. Please feel free to reopen a new issue if this is still a problem. Thanks!
